### ISSUE TITLE
Add warnings around current versions EOL date

### ISSUE THREAD

**Issue by jedcunningham** [astronomer/astronomer-airflow-version-check#63]
Now that we have https://github.com/astronomer/astro-runtime/issues/1039 done, we should add some notifications:

- when the current version will be EOL in, say, 30 days or less
- when the current version is already EOL

**Comment by vatsrahul1001** [comment]
@jedcunningham we can close this right? as its covered in https://github.com/astronomer/astro-runtime/pull/1208

**Comment by jedcunningham** [comment]
No, this is different. This is to add a warning to the Airflow UI when EOL is upcoming. That just automated deprecation on our side.

**Comment by phanikumv** [comment]
This could be a part of runtime 11.6

**Comment by phanikumv** [comment]
To be tested for upgrade and downgrade scenarios

**Comment by sunank200** [comment]
@vatsrahul1001 and me have discussed and prepare following test cases: https://www.notion.so/astronomerio/Astro-runtime-version-EOL-54ab13b840434fccbcc03b60e2eddabd

**Comment by sunank200** [comment]
All the changes has been done as per PR comments - test to be done from @vatsrahul1001 side
