### ISSUE TITLE
Add warning when current Runtime version has been yanked

### ISSUE THREAD

**Issue by jedcunningham** [astronomer/astronomer-airflow-version-check#68]
If an Airflow instance is running on a yanked Runtime version, we should add a warning in the Airflow UI.

**Comment by phanikumv** [comment]
Linked to https://github.com/astronomer/astronomer-airflow-version-check/issues/63

**Comment by phanikumv** [comment]
Will close this by tomorrow

**Comment by sunank200** [comment]
I have tested the change but yanked on the current version should not show. I am adding that logic and fixing it. I should be able to close this today.

**Comment by phanikumv** [comment]
Working on the review comments
